<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $books = [
            [
                'id' => 1,
                'name' => 'IELTS 5 Practice Tests',
                'isbn' => '0648000079',
                'author' => 'Robert Nicholson ',
                'description' => 'General Set 5 from ‘High Scorer’s Choice’ series contains 5 full length IELTS practice tests (no. 21-25) and is a must-have study tool to achieve a high band score in IELTS. These tests feel as authentic as the real IELTS papers, and doing them at home is a great way to estimate your real IELTS score. Being a demanding test, IELTS requires a thorough preparation and these tests will help you master exam strategies, polish your techniques and raise your confidence.',
                'category' => 1,
                'ratings' => '4',
                'price' => 32.94,
                'image' => 'ielts_5_practice_tests.jpg',
                'publisher' => 'Cambridge University',
                'publication_date' => "2020-07-15",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'name' => 'Collins Practice Tests for IELTS',
                'isbn' => '0007499698',
                'author' => 'Harpercollins Uk',
                'description' => 'Prepare yourself thoroughly for the IELTS exam By using Practice Tests for IELTS, you will: Feel completely confident about how the IELTS exam works; Know what to expect on the day of the exam;Improve your score through realistic practice',
                'category' => 1,
                'ratings' => '4',
                'price' => 19.25,
                'image' => 'collins_practice_tests_for_ielts.jpg',
                'publisher' => 'Cambridge University',
                'publication_date' => "2013-06-03",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'name' => 'Maths Book for 6-7 Year Olds',
                'isbn' => '979-8668701858',
                'author' => 'Jungle Publishing',
                'description' => 'Year 2 Maths: Hoping to Stay Ahead?This is a Maths Workbook covering the National Curriculum for Year 2.',
                'category' => 2,
                'ratings' => '4',
                'price' => 12.99,
                'image' => 'maths_book_for_6_7_year_old.jpg',
                'publisher' => 'Independently published',
                'publication_date' => "2020-08-09",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'name' => 'Maths Book for 10-11 Year Olds',
                'isbn' => '1914329031',
                'author' => 'Jungle Publishing',
                'description' => 'This is a Maths Workbook covering the National Curriculum for Y6 - Perfect for SATs preparation',
                'category' => 2,
                'ratings' => '3',
                'price' => 11.99,
                'image' => 'maths_book_for_10_11_year_old.jpg',
                'publisher' => 'Independently published',
                'publication_date' => "2021-08-15",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'name' => 'PHP Programming for Beginners',
                'isbn' => '979-8320792606',
                'author' => 'Liam Peterson',
                'description' => 'This comprehensive guide demystifies PHP for newcomers, offering step-by-step direction from the basics of PHP programming to more advanced topics. Each chapter is carefully structured to cover key concepts and provide practical code examples.',
                'category' => 3,
                'ratings' => '5',
                'price' => 25.95,
                'image' => 'php_programming_for_beginners.jpg',
                'publisher' => 'Independently published',
                'publication_date' => "2024-03-24",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'name' => 'Modern PHP: New Features and Good Practices',
                'isbn' => '1491905018',
                'author' => 'Josh Lockhart',
                'description' => "PHP is experiencing a renaissance, though it may be difficult to tell with all of the outdated PHP tutorials online. With this practical guide, you'll learn how PHP has become a full-featured, mature language with object-orientation, namespaces, and a growing collection of reusable component libraries. Author Josh Lockhart-creator of PHP The Right Way, a popular initiative to encourage PHP best practices-reveals these new language features in action. You'll learn best practices for application architecture and planning, databases, security, testing, debugging, and deployment. If you have a basic understanding of PHP and want to bolster your skills, this is your book.",
                'category' => 3,
                'ratings' => '5',
                'price' => 36.9,
                'image' => 'modern_php.jpg',
                'publisher' => 'O"Reilly Media, Inc, USA; 1st edition',
                'publication_date' => "2015-02-20",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'name' => 'PHP Cookbook: Modern Code Solutions for Professional',
                'isbn' => '1098121325',
                'author' => 'Eric A. Mann',
                'description' => "If you're a PHP developer looking for proven solutions to common problems, this cookbook provides code recipes to help you resolve a variety of coding issues. PHP is a remarkably easy language to work with, which explains why it powers more than 75% of the websites online today. It's also incredibly forgiving of programming mistakes, which can perpetuate reuse of questionable code. By leveraging modern versions of PHP through version 8.2, author Eric Mann provides self-contained recipes that will enable you to solve the problems you face in your day-to-day work. You'll also find established patterns and examples that any developer can follow for addressing common problems with PHP. With these recipes, you'll quickly identify and resolve complicated issues without having to reinvent the wheel.",
                'category' => 3,
                'ratings' => '5',
                'price' => 48.36,
                'image' => 'php_cookbook.jpg',
                'publisher' => 'O"Reilly Media',
                'publication_date' => "2023-06-20",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'name' => 'Dark Operator: A Military Science Fiction Special Forces',
                'isbn' => '1949731472',
                'author' => 'Doc Spears, Jason Anspach, Nick Cole ',
                'description' => "Tasked with performing covert missions, its kill teams are filled with the best warriors from within the ranks of the Legion. Kel Turner is one of the youngest legionnaires ever to be selected to its ranks. After many battles and trials, he is faced with the greatest challenge of his life - operating by himself on a remote planet at the galaxy's edge, a foot soldier for the policies of the duplicitous House of Reason, tasked with solving a crisis that would take ten kill teams to resolve.",
                'category' => 4,
                'ratings' => '3',
                'price' => 7.06,
                'image' => 'dark_operator.jpg',
                'publisher' => 'Galaxy"s Edge Press',
                'publication_date' => "2020-05-27",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'name' => 'The Dark Forest (The Three-Body Problem Book 2)',
                'isbn' => '1077670249',
                'author' => 'Cixin Liu, Joel Martinsen',
                'description' => 'Read the award-winning, critically acclaimed, multi-million-copy-selling science-fiction phenomenon – soon to be a Netflix Original Series from the creators of Game of Thrones.',
                'category' => 4,
                'ratings' => '1',
                'price' => 12.99,
                'image' => 'the_dark_forest.jpg',
                'publisher' => 'Head of Zeus',
                'publication_date' => "2015-08-11",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'name' => 'The Adventures Of Sherlock Holmes',
                'isbn' => '979-8325405198',
                'author' => 'Arthur Conan Doyle',
                'description' => "Expert Annotations by Norris Elliott: Delve into the intriguing world of Sherlock Holmes with insightful annotations by Norris Elliott, providing context and analysis of the stories' themes, characters, and deduction methods.",
                'category' => 5,
                'ratings' => '5',
                'price' => 31.64,
                'image' => 'the_adventures_of_sherlock_holmes.jpg',
                'publisher' => 'Independently published',
                'publication_date' => "2024-05-11",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'name' => 'C# and Algorithmic Thinking for the Complete Beginner',
                'isbn' => '979-8865989462',
                'author' => 'Aristides Bouras',
                'description' => "Completely updated for the latest version of C#, this book offers a comprehensive introduction to programming, assuming no prior knowledge of the subject. It is designed for individuals, eager to learn C# from scratch, providing a strong foundation in Algorithmic Thinking—the fundamental skill every aspiring programmer must acquire. Algorithmic Thinking encompasses more than just writing code; it entails mastering the art of problem-solving through coding.",
                'category' => 3,
                'ratings' => '5',
                'price' => 83.18,
                'image' => 'C_sharp_and_algorithmic_thinking.jpg',
                'publisher' => 'Independently published',
                'publication_date' => "2024-05-14",
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('books')->insert($books);
    }
}
